// src/OfflineLibrary.vue
<template>
    <Navigation active="local"/>
    <div class="modal" v-if="displayBookContextMenu">
      <div><b>{{
          // @ts-ignore
          displayBookContextMenu.title!
        }}</b></div>
      <button @click="deleteBook(displayBookContextMenu)">Delete from device</button>
      <button @click="closeModal">Abort</button>
    </div>
    <div style="display: flex; flex-wrap: wrap;">
      <div
        v-for="book in offlineBooks"
        :key="book.id"
        :title="book.title"
        @click="goToBook(book.id!)"
        @contextmenu="openContextMenu($event, book)"
        style="cursor: pointer;">
        <BookCoverThumbnail :book="book" :image="`url(${book.cover})`"/>
      </div>
    </div>
</template>


<script setup lang="ts">
import {onMounted, ref} from 'vue'
import {getValuesFromIndexedDB, loadFromIndexedDB} from './dbaccess'
import BookCoverThumbnail from "./BookCoverThumbnail.vue";
import Navigation from "./Navigation.vue";

const displayBookContextMenu = ref(null)

function openContextMenu(event, book) {
  event.preventDefault()
  displayBookContextMenu.value = book
}

function deleteBook(book) {
  // TODO: Delete from Device
  displayBookContextMenu.value = null
}

function closeModal() {
  displayBookContextMenu.value = null
}

type BookEntry = {
  id?: string
  cover?: string
  data: {
    identifier: string
    title: string
    progress?: { lastUpdated?: number }
    [k: string]: any
  }
  [k: string]: any
}

const offlineBooks = ref<BookEntry[]>([])

async function loadOfflineBooks() {
  try {
    const bks = (await getValuesFromIndexedDB('books', 'books')) as BookEntry[]
    bks.sort((a, b) => {
      const al = a?.progress?.lastUpdated ?? 0
      const bl = b?.progress?.lastUpdated ?? 0
      return bl - al
    })
    for (let book of bks) {
      // @ts-ignore
      book.cover = await loadFromIndexedDB('cover', 'cover', book.id!)
    }
    console.log(bks)
    offlineBooks.value = bks
  } catch (e) {
    window.location.href = '/#lib'
  }
}

function goToBook(id: string) {
  window.location.href = `/#book?id=${id}`
}

onMounted(() => {
  loadOfflineBooks()
})
</script>

// src/OfflineLibrary.tsx
import React, {useEffect, useRef, useState} from 'react'
import {getValuesFromIndexedDB, loadFromIndexedDB, saveToIndexedDB} from "./dbaccess";


export const OfflineLibrary = () => {
    const [offlineBooks, setOfflineBooks] = useState([])
    let initialized = false

    async function loadOfflineBooks() {
        try {
            const bks = await getValuesFromIndexedDB("books", "books")
            console.log(bks)
            // @ts-ignore
            bks.sort((a,b) => b.data.progress.lastUpdated - a.data.progress.lastUpdated);
            // @ts-ignore
            setOfflineBooks(bks)
        } catch (e) {
            window.location.href = "/library"
        }
    }

    useEffect(() => {
        if (!initialized) {
            initialized = true;
            loadOfflineBooks();
        }
    }, [])

    // @ts-ignore
    const l = [offlineBooks.map(book => <div title={book.data.title} onClick={() => {window.location.href=`/book#id=${book.data.identifier}`}} key={book.data.identifier} style={{cursor: "pointer"}}>
        <div style={
            {
                padding: "5px",
                margin: "1rem",
                fontWeight: "bold",
                whiteSpace: "nowrap",
                textOverflow: "ellipsis",
                overflow: "hidden",
                width: "15em",
                height: "23em",
            }}>
            <div style={{
                // @ts-ignore
                backgroundImage: `url(data:image/png;base64,${book.cover})`,
                width: "100%",
                height: "calc(100% - 2rem)",
                border: "1px solid #000",
                borderRadius: "5px",
                marginBottom: "5px",
            }}></div>
            {
                    // @ts-ignore
                    book.data.title
            }
            </div>
    </div>)]
    // Saved to localstorage
    return (
        <div>
            <div>
                <a href={"/"}>Offline Library</a>
                <a href={"/library"}>Library</a>
            </div>
            <div>
                Offline Library
            </div>
            <div style={{display: "flex", flexWrap: "wrap"}}>
                {l}
            </div>
        </div>
    )
}
export default OfflineLibrary
